name: Mirror to GitLab

on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOCKEN }}@gitlab.com/xerofenix/git-jwt.git || echo "Remote already exist"
          git fetch gitlab || echo "No existing remote to fetch"
          git push gitlab main --force # Change this to your default branch if it's different
